#!/usr/bin/env bash
# Mock Claude CLI — outputs stream-json format.
# Uses ORCA_MOCK_MODE env var or detects interaction type from prompt.

set -euo pipefail

PROMPT=""
MODEL=""
SESSION_ID="mock-session-$(date +%s)-$$"

while [[ $# -gt 0 ]]; do
  case "$1" in
    -p) PROMPT="$2"; shift 2 ;;
    --model) MODEL="$2"; shift 2 ;;
    --resume) SESSION_ID="$2"; shift 2 ;;
    *) shift ;;
  esac
done

emit_text() {
  printf '{"type":"stream_event","event":{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":%s}}}\n' \
    "$(printf '%s' "$1" | jq -Rs .)"
}

emit_result() {
  echo "{\"type\":\"stream_event\",\"event\":{\"type\":\"result\",\"session_id\":\"$SESSION_ID\",\"usage\":{\"input_tokens\":100,\"output_tokens\":50},\"total_cost_usd\":0.001}}"
}

# Detect mode from env or prompt content
MODE="${ORCA_MOCK_MODE:-}"
if [[ -z "$MODE" ]]; then
  if echo "$PROMPT" | grep -q 'task complexity evaluator'; then
    MODE="${ORCA_MOCK_EVALUATE_MODE:-evaluate}"
  elif echo "$PROMPT" | grep -q 'You are a code reviewer'; then
    MODE="${ORCA_MOCK_REVIEW_MODE:-review}"
  elif echo "$PROMPT" | grep -q 'implementation planner'; then
    MODE="plan"
  elif echo "$PROMPT" | grep -q 'task breaker\|decompose.*subtasks\|break.*down.*goal'; then
    MODE="breakdown"
  else
    MODE="code"
  fi
fi

case "$MODE" in
  evaluate)
    emit_text '{"needs_breakdown": false, "confidence": 0.9, "reasoning": "Single concern task.", "suggested_subtask_count": 0, "needs_user_input": false, "user_input_question": ""}'
    emit_result
    ;;
  evaluate_breakdown)
    emit_text '{"needs_breakdown": true, "confidence": 0.85, "reasoning": "Multiple files and concerns.", "suggested_subtask_count": 3, "needs_user_input": false, "user_input_question": ""}'
    emit_result
    ;;
  evaluate_input)
    emit_text '{"needs_breakdown": false, "confidence": 0.7, "reasoning": "Ambiguous requirements.", "suggested_subtask_count": 0, "needs_user_input": true, "user_input_question": "Which database should be used: Postgres or SQLite?"}'
    emit_result
    ;;
  plan)
    emit_text '## Implementation Plan\n\n## Step 1: Analyze\nReview the current codebase.\n\n## Step 2: Implement\nMake the required changes.\n\n## Step 3: Verify\nRun tests to confirm correctness.'
    emit_result
    ;;
  review)
    emit_text '```json\n{"approved": true, "feedback": "Code looks good. Clean implementation.", "checks": [{"key": "correctness", "label": "Correctness", "passed": true}], "findings": [{"id": "f1", "summary": "All changes look correct", "passed": true}]}\n```'
    emit_result
    ;;
  review_reject)
    emit_text '```json\n{"approved": false, "feedback": "Missing error handling in the main function.", "checks": [{"key": "correctness", "label": "Correctness", "passed": false}], "findings": [{"id": "f1", "summary": "No error handling", "passed": false}]}\n```'
    emit_result
    ;;
  breakdown)
    emit_text '```json\n[{"title": "Analyze requirements", "description": "Review existing code", "dependsOnIndices": [], "suggestedTool": "claude"}, {"title": "Implement changes", "description": "Apply the implementation", "dependsOnIndices": [0], "suggestedTool": "claude"}]\n```'
    emit_result
    ;;
  code)
    if [[ -f "$PWD/orca-mock-output.txt" ]]; then
      # Append to produce a new diff on re-runs (review rejection loop)
      echo "// revision $(date +%s)-$$" >> "$PWD/orca-mock-output.txt"
    else
      cat > "$PWD/orca-mock-output.txt" << 'FILECONTENT'
// Generated by mock claude for testing
export function hello(): string {
  return 'hello from orca mock';
}
FILECONTENT
    fi
    emit_text 'I have created orca-mock-output.txt with the requested implementation.'
    emit_result
    ;;
  error)
    echo "Error: mock forced failure" >&2
    exit 1
    ;;
  empty)
    emit_result
    ;;
  *)
    emit_text "Unknown mode: $MODE"
    emit_result
    ;;
esac

exit 0
