/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as TaskIdRouteImport } from './routes/$taskId'
import { Route as IndexRouteImport } from './routes/index'

const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskIdRoute = TaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$taskId': typeof TaskIdRoute
  '/config': typeof ConfigRoute
  '/memory': typeof MemoryRoute
  '/queue': typeof QueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$taskId': typeof TaskIdRoute
  '/config': typeof ConfigRoute
  '/memory': typeof MemoryRoute
  '/queue': typeof QueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$taskId': typeof TaskIdRoute
  '/config': typeof ConfigRoute
  '/memory': typeof MemoryRoute
  '/queue': typeof QueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$taskId' | '/config' | '/memory' | '/queue'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$taskId' | '/config' | '/memory' | '/queue'
  id: '__root__' | '/' | '/$taskId' | '/config' | '/memory' | '/queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaskIdRoute: typeof TaskIdRoute
  ConfigRoute: typeof ConfigRoute
  MemoryRoute: typeof MemoryRoute
  QueueRoute: typeof QueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$taskId': {
      id: '/$taskId'
      path: '/$taskId'
      fullPath: '/$taskId'
      preLoaderRoute: typeof TaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaskIdRoute: TaskIdRoute,
  ConfigRoute: ConfigRoute,
  MemoryRoute: MemoryRoute,
  QueueRoute: QueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
